<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Crash id generated by the IoT unit. The same crash can reach the server
     * twice — from the phone after its countdown and from the device's Wi-Fi
     * backup — so this id keeps it to a single alert (and a single SMS round).
     */
    public function up(): void
    {
        Schema::table('emergency_alerts', function (Blueprint $table) {
            $table->string('event_uid', 64)->nullable()->unique()->after('user_id');
            $table->string('source', 10)->default('phone')->after('event_uid')->comment('phone | iot');
        });
    }

    public function down(): void
    {
        Schema::table('emergency_alerts', function (Blueprint $table) {
            $table->dropUnique(['event_uid']);
            $table->dropColumn(['event_uid', 'source']);
        });
    }
};
